spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/easyshop
    username: postgres
    password: postgres1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # or "create" if you want to start fresh
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#
#  sql:
#    init:
#      mode: always

jwt:
  secret: 2f81f6a9a5c24e2f94b9d3f8d40358dfaf29dd274c7d489b82a1f46e44c29e377d97e80e4382d1c3e3b4d5f42ff3de39
  expiration: 86400000 # 1 day in milliseconds
